source:
  host: '127.0.0.1'
  port: 5672
  username: 'username'
  password: 'password'
  virtual_host: '/virtual_host'
  queue: 'queue_a'
  receive_rate: 100 # messages per second
sink:
  host: '127.0.0.1'
  port: 5672
  username: 'username'
  password: 'password'
  virtual_host: '/virtual_host'
  queue: 'queue_b'